# Generated by Django 4.0.3 on 2022-04-12 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/events/%Y/%m/%d', verbose_name='Фото')),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('communication', models.TextField(blank=True, verbose_name='Контакты')),
                ('location', models.TextField(blank=True, verbose_name='Место проведения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зарегистрирован?')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events', verbose_name='Мероприятие')),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация на мероприятие',
                'verbose_name_plural': 'Регистрация на мероприятия',
            },
        ),
    ]
