# Generated by Django 4.0.3 on 2022-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_alter_customuser_vk_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/', verbose_name='Аватар'),
        ),
    ]
