# Generated by Django 4.0.3 on 2022-06-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/avatar/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
